<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-24T19:56:49 IST" name="Default suite" finished-at="2022-05-24T19:57:34 IST" duration-ms="45225">
    <groups>
    </groups>
    <test started-at="2022-05-24T19:56:49 IST" name="Default test" finished-at="2022-05-24T19:57:34 IST" duration-ms="45225">
      <class name="com.accuweather.uiLayer">
        <test-method is-config="true" signature="BeforeTest()[pri:0, instance:com.accuweather.uiLayer@562457e1]" started-at="2022-05-24T19:56:49 IST" name="BeforeTest" finished-at="2022-05-24T19:56:49 IST" duration-ms="73" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeTest -->
        <test-method signature="getinfo()[pri:1, instance:com.accuweather.uiLayer@562457e1]" started-at="2022-05-24T19:56:49 IST" name="getinfo" description="Testcase to  get weather information" finished-at="2022-05-24T19:57:33 IST" duration-ms="43673" status="FAIL">
          <exception class="com.utility.customException">
            <message>
              <![CDATA[temprature of two sources have variance]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.utility.customException: temprature of two sources have variance
at com.accuweather.uiLayer.getinfo(uiLayer.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.utility.customException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getinfo -->
      </class> <!-- com.accuweather.uiLayer -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
